program: proteinvirtual/train.py
method: grid
name: egnn_hierarchy_p_sweep_smaller
project: protein_virtual
metric: # Does not matter, as we are using sweep to run the experiment.
  goal: maximize
  name: val/graph_label/accuracy

parameters:
  task:
    value: multiclass_graph_classification

  dataset:
    value: fold_fold

  encoder:
    value: gnn_geo_hetero_hierarchy

  encoder.emb_dim:
    value: 256

  encoder.num_layers:
    value: 4

  decoder.graph_label.dropout:
    value: 0.5

  optimiser.optimizer.lr:
    value: 0.001

  features:
    value: geo_hetero_hierarchy_p

  features.virtual_nodes.secondary.p_nodes:
    values: [0.01, 0.05, 0.1, 0.2]

  scheduler:
    value: plateau

  extras.enforce_tags:
    value: False

  trainer:
    value: gpu

  trainer.max_epochs:
    value: 50

  logger:
    value: wandb

  name:
    value: "${hydra:runtime.choices.features}_${hydra:runtime.choices.encoder}_${encoder.emb_dim}channels_${encoder.num_layers}layers"

  test:
    value: True

  dataset.datamodule.batch_size:
    value: 16

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
