_target_: "proteinvirtual.models.graph_encoders.gnn.VirtualGNN"
num_layers: 6 # Number of message passing layers
layer_types: # Custom message passing layers per each hierarchy
  r_to_r:
    pairs: [[real, real]]
    n_dims: [512] # Dimension of the node embeddings
    layers: ["GCN"]
  rv_mutual:
    pairs: [[real, virtual]]
    n_dims: [512] # Dimension of the node embeddings
    layers: ["GCN"]
  v_to_v_upwards: 
    pairs: [[secondary, tertiary], [tertiary, root]]  # Pairs of node types to connect, efficient shorthand for From and To
    n_dims: [512, 512] # Dimension of the node embeddings
    layers: ["GCN", "GCN"]
  v_to_v_downwards:
    pairs: [[tertiary, secondary], [root, tertiary]]
    n_dims: [512, 512] # Dimension of the node embeddings
    layers: ["GCN", "GCN"]
activation: relu
aggr: "sum"
pool: "mean"
dropout: 0.0
