program: proteinvirtual/train.py
method: grid
name: schnet_cath_p_sweep_smaller
project: protein_virtual
metric: # Does not matter, as we are using sweep to run the experiment.
  goal: maximize
  name: val/residue_type/accuracy

parameters:
  task:
    value: inverse_folding

  dataset:
    value: cath

  encoder:
    value: virtual_schnet

  encoder.hidden_channels:
    value: 256

  encoder.num_layers:
    value: 4

  decoder.residue_type.dropout:
    value: 0.5

  optimiser.optimizer.lr:
    value: 0.001

  features:
    value: geo_hetero_p_inverse_fold

  features.virtual_nodes.virtual.p_nodes:
    values: [0.01, 0.05, 0.1, 0.2]

  scheduler:
    value: plateau

  extras.enforce_tags:
    value: False

  trainer:
    value: gpu

  trainer.max_epochs:
    value: 35

  logger:
    value: wandb

  name:
    value: "${hydra:runtime.choices.features}_${hydra:runtime.choices.encoder}_${encoder.hidden_channels}channels_${encoder.num_layers}layers"

  test:
    value: True

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
