_target_: proteinvirtual.features.factory.VirtualProteinFeaturiser
representation: CA
virtual_nodes:
  virtual:
    n_nodes: 10
    positions: random
edge_types: # Custom types for different edges
  r_to_r:
    from: real
    to: real
    strategies:
      - knn_16
  v_to_r:
    from: virtual
    to: real
    strategies:
      - full
  r_to_v:
    from: real
    to: virtual
    strategies:
      - full
  v_to_v:
    from: virtual
    to: virtual
    strategies:
      - full
scalar_node_features:
  real:
    - amino_acid_one_hot
    - sequence_positional_encoding
  virtual:
    - random_32
vector_node_features: {}
scalar_edge_features:
  r_to_r:
    - edge_distance
  v_to_r: 
    - random_16
  r_to_v:
    - random_16
  v_to_v:
    - random_32
vector_edge_features: {}