_target_: proteinvirtual.features.factory.VirtualProteinFeaturiser
representation: CA
virtual_nodes:
  secondary:
    n_nodes: 10
    positions:
      type: fps
      basis: real
  tertiary:
    n_nodes: 5
    positions:
      type: fps
      basis: secondary
  root:
    n_nodes: 1
    positions:
      type: fps
      basis: tertiary
edge_types: # Custom types for different edges
  edge:
    pairs: _all_
    strategies:
      - knn_10
      - eps_8
scalar_node_features:
  real:
    - amino_acid_one_hot
  _notreal_:
    - random_16
vector_node_features:
  real: ["orientation"]
  _notreal_: [] # Efficient shorthand for all node types 
scalar_edge_features:
  _all_:
    - edge_distance
    - edge_type
    - node_features
    - sequence_distance
vector_edge_features: 
  _all_: ["edge_vectors"]
