_target_: proteinvirtual.features.factory.VirtualProteinFeaturiser
representation: CA
virtual_nodes:
  secondary:
    p_nodes: 0.1
    positions: fps
  tertiary:
    n_nodes: 8
    positions: fps
  root:
    n_nodes: 1
edge_types: # Custom types for different edges
  r_to_r:
    strategies:
      - knn_16
  r_to_v:
    pairs: [[real, secondary]]
    strategies:
      - knn_16
  v_to_r:
    pairs: [[secondary, real]]
    strategies:
      - knn_16
  secondary_tertiary:
    pairs: [[secondary, tertiary]]
    strategies:
      - knn_16
  tertiary_root:
    pairs: [[tertiary, root]] 
    strategies:
      - full
  root_tertiary:
    pairs: [[root, tertiary]]
    strategies:
      - full
  tertiary_secondary:
    pairs: [[tertiary, secondary]]
    strategies:
      - knn_16
scalar_node_features:
  real:
    - amino_acid_one_hot
    - sequence_positional_encoding
    - alpha
    - kappa
    - dihedrals
  secondary:
    - type: navg
      basis: real
      k: 16
  tertiary:
    - random_64
  root:
    - random_128
vector_node_features: {}
scalar_edge_features:
  r_to_r:
    - edge_distance
  r_to_v:
    - edge_distance
  v_to_r:
    - edge_distance
  tertiary_secondary:
    - zero_0
  secondary_tertiary:
    - zero_0
  tertiary_root:
    - zero_0
  root_tertiary:
    - zero_0
vector_edge_features: {}
