_target_: proteinvirtual.features.factory.VirtualProteinFeaturiser
representation: CA
virtual_nodes:
  virtual:
    n_nodes: 16
    positions: random
edge_types: # Custom types for different edges
  r_to_r:
    strategies:
      - knn_16
  v_to_r:
    pairs: [[virtual, real]]
    strategies:
      - ${vedge_t}
  r_to_v:
    pairs: [[real, virtual]]
    strategies:
      - ${vedge_t}
  v_to_v:
    pairs: [[virtual, virtual]]
    strategies:
      - ${vedge_t}
scalar_node_features:
  real:
    - amino_acid_one_hot
    - sequence_positional_encoding
    - alpha
    - kappa
    - dihedrals
  virtual:
    - type: navg
      basis: real
      k: 16
vector_node_features: {}
scalar_edge_features:
  r_to_r:
    - edge_distance
  v_to_r: 
    - ${vedge_sf}
  r_to_v:
    - ${vedge_sf}
  v_to_v:
    - ${vedge_sf}
vector_edge_features: {}