_target_: proteinvirtual.features.factory.VirtualProteinFeaturiser
representation: CA
virtual_nodes:
  secondary:
    n_nodes: 10
  tertiary:
    n_nodes: 5
  root:
    n_nodes: 1
edge_types: # Custom types for different edges
  r_to_r:
    from: real
    to: real
    strategies:
      - knn_16
  r_to_v:
    pairs: [[real, secondary]]
    strategies:
      - full
  v_to_r:
    pairs: [[secondary, real]]
    strategies:
      - full
  v_to_v_upwards:
    pairs: [[secondary, tertiary], [tertiary, root]] # Pairs of node types to connect, efficient shorthand for From and To
    strategies:
      - full
  v_to_v_downwards:
    pairs: [[tertiary, secondary], [root, tertiary]]
    strategies:
      - full
scalar_node_features:
  real:
    - amino_acid_one_hot
    - sequence_positional_encoding
    - alpha
    - kappa
    - dihedrals
  _notreal_:
    - random_32
vector_node_features: {}
scalar_edge_features:
  r_to_r:
    - edge_distance
  rv_mutual:
    - random_16
  v_to_v_upwards:
    - random_16
  v_to_v_downwards:
    - random_16
vector_edge_features: {}
