_target_: proteinvirtual.features.factory.VirtualProteinFeaturiser
representation: CA
virtual_nodes: []
edge_types: # Custom types for different edges
  r_to_r:
    strategies:
      - knn_16
scalar_node_features:
  real:
    - amino_acid_one_hot
    - sequence_positional_encoding
    - alpha
    - kappa
    - dihedrals
vector_node_features: {}
scalar_edge_features:
  r_to_r:
    - edge_distance
vector_edge_features: {}
