_target_: proteinvirtual.models.graph_encoders.virtgat.RealGAT
num_layers: 6
in_channels: -1
hidden_channels: 512
out_channels: 512
dropout: 0.3
v2: True
act: leakyrelu
norm: layernorm

# GATConv Parameters
# residual: True
edge_dim: 1
add_self_loops: False
