_target_: "proteinvirtual.models.graph_encoders.gnn.VirtualGNN"
num_layers: 3 # Number of message passing layers
emb_dim: 256 # Dimension of the node embeddings
layer_types: # Custom message passing layers per each hierarchy
  r_to_r:
    pairs: [[real, real]]
    layers: ["EGNN"]
  rv_mutual:
    pairs: [[real, virtual], [virtual, real]]
    layers: ["EGNN", "EGNN"]
  v_to_v:
    pairs: [[virtual, virtual]]
    layers: ["EGNN"]
activation: relu
aggr: "sum"
pool: "mean"
dropout: 0.1
pos_features: True
edge_features: False
residual: True
