_target_: "proteinvirtual.models.graph_encoders.gnn.VirtualGNN"
num_layers: 6 # Number of message passing layers
emb_dim: 512 # Dimension of the node embeddings
layer_types: # Custom message passing layers per each hierarchy
  r_to_r:
    pairs: [[real, real]]
    layers: ["GCN"]
  r_to_v:
    pairs: [[real, secondary]]
    layers: ["GCN"]
  v_to_v_upwards: 
    pairs: [[secondary, tertiary], [tertiary, root]]  # Pairs of node types to connect, efficient shorthand for From and To
    layers: ["GCN", "GCN"]
  v_to_v_downwards:
    pairs: [[tertiary, secondary], [root, tertiary]]
    layers: ["GCN", "GCN"]
  v_to_r:
    pairs: [[secondary, real]]
    layers: ["GCN"]
activation: relu
aggr: "sum"
pool: "mean"
dropout: 0.1
pos_features: False
edge_features: False
residual: True
